# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           /posts/:title/
permalink:           pretty
relative_permalinks: true

# Setup
title:               FourtySeven
tagline:             '나는 개발자로소이다'
description:         '<a href="http://rubyonrails.org/"><img src="http://i.imgur.com/sGs4YqE.png" title="source: imgur.com" /></a><br><a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a> is an open-source web framework that’s optimized for programmer happiness and sustainable productivity.<br> It lets you
write beautiful code by favoring convention over configuration.'
url:                 http://fourtyseven.5oclock.io
baseurl:             'http://fourtyseven.5oclock.io'
paginate:            3

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/5oclock_io
  email:             zorba@5oclock.io

# Custom vars
version:             1.1.0
