# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               RubyonRails Developer
tagline:             'yourWebApp.valid?'
description:         '<a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a> is an open-source web framework that’s optimized for programmer happiness and sustainable productivity. It lets you
write beautiful code by favoring convention over configuration.'
url:                 http://5oclock.github.io
baseurl:             'http://5oclock.github.io/'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
